language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t multi-conatiner-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true multi-conatiner-test npm test -- --coverage
